---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
.yardopts:
  delete: true
Rakefile:
  linter_options:
    - ignore-paths=./spec/*
    - no-80chars-check
    - no-autoloader_layout-check
    - no-puppet_url_without_modules-check
